Module5 task2
htmlacademy-react/78842-six-cities-7 pull request #10
Opened 2021-06-24 15:46 UTC by VadimCpp

2021-06-25 07:51 UTC, Antoshka007 requested changes

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/cities-map/cities-map.jsx
> +            .marker(coords, {activeIcon})
Это было причиной ошибки:
```suggestion
            .marker(coords, {icon: activeIcon})
```

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/cities-map/cities-map.jsx
> +  }, [city, offers, activeOfferId]);
При изменении активного оффера у тебя выполняется весь useEffect.
Карта связывается с DOM-элементом, создаются новые маркеры.
Какое-то чудо, что это работает без ошибок)
Я предлагаю при изменении активного оффера просто менять иконки у уже созданных маркеров. Можно сохранить информацию об оффер-маркер в ref и тогда получится что-то типа такого:
```js
  const markers = useRef([]);

  ....

  useEffect(() => {
    markers.current.forEach(({ markerLayer, offerId}) => {
      if (offerId === activeOfferId) {
        markerLayer.setIcon(ICON_ACTIVE);
      } else {
        markerLayer.setIcon(ICON);
      }
    });
  }, [activeOfferId]);
```
`markerLayer` - это то, что возвращает `leaflet.marker(coords, {icon}).addTo(map.current)`

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/cities-map/cities-map.jsx
> +  }, [city, offers, activeOfferId]);
Также было бы хорошо очищать маркеры перед созданием новых маркеров `markerLayer.remove()`, когда меняются офферы.

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/main-screen/main-screen.jsx
> +      offersForCity = offersForCity.sort((a, b) => a.price - b.price);
Метод sort выполняется сортировку на месте. Поэтому переприсваивание тут лишнее.

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/offers/offers.jsx
> +  useEffect(() => onActiveOfferSet(activeOfferId), [ activeOfferId, onActiveOfferSet ]);
Сложнова-то вышло.  При первом рендере тоже будет вызван onActiveOfferSet.
`activeOfferId` тебе тут не нужен. Поэтому `onMouseEnter`, `onMouseLeave` ты можешь сразу вызывать `onActiveOfferSet` и отказаться от `const [activeOfferId, setActiveOfferId] = useState(0);`.

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/sorting/sorting.jsx
> +  const [ type, setType ] = useState(SortingTypes.POPULAR);
Получается, у тебя это состояние дублируется тут и в MainScreen. Предлагаю оставить только в MainScreen.

2021-06-25 07:51 UTC, Antoshka007 commented on project/src/components/sorting/sorting.jsx
> +function Sorting({ initialSorting = SortingTypes.POPULAR, onSortingChange = () => {} }) {
`initialSorting` не используется

2021-06-26 14:26 UTC, VadimCpp commented on project/src/components/cities-map/cities-map.jsx
> +            .marker(coords, {activeIcon})
Ага, невнимательно было)

2021-06-26 15:29 UTC, VadimCpp commented on project/src/components/cities-map/cities-map.jsx
> +  }, [city, offers, activeOfferId]);
Исправлено

2021-06-26 15:34 UTC, VadimCpp commented on project/src/components/sorting/sorting.jsx
> +  const [ type, setType ] = useState(SortingTypes.POPULAR);
Убрал

2021-06-26 15:41 UTC, VadimCpp commented on project/src/components/offers/offers.jsx
> +  useEffect(() => onActiveOfferSet(activeOfferId), [ activeOfferId, onActiveOfferSet ]);
Убрано

2021-06-26 15:41 UTC, VadimCpp commented on project/src/components/sorting/sorting.jsx
> +function Sorting({ initialSorting = SortingTypes.POPULAR, onSortingChange = () => {} }) {
Убрано

2021-06-26 15:46 UTC, VadimCpp commented on project/src/components/main-screen/main-screen.jsx
> +      offersForCity = offersForCity.sort((a, b) => a.price - b.price);
Исправлено

2021-06-26 20:05 UTC, Antoshka007 approved these changes

2021-06-26 20:05 UTC, Antoshka007 commented on project/src/components/cities-map/cities-map.jsx
> +      markers.current.length = 0;
Оу, выглядит крипово)
Почему не `markers.current = []`?

2021-06-26 20:05 UTC, Antoshka007 commented on project/src/components/cities-map/cities-map.jsx
> +  }, [offers, activeOfferId]);
Получается, что при изменении активного маркера, всё перерисовывается, но ок)

2021-06-26 20:05 UTC, merged

2021-06-27 10:52 UTC, VadimCpp commented on project/src/components/cities-map/cities-map.jsx
> +      markers.current.length = 0;
Обсудим на созвоне