Module6 task3
htmlacademy-react/78842-six-cities-7 pull request #15
Opened 2021-07-01 22:37 UTC by VadimCpp

2021-07-03 06:59 UTC, Antoshka007 requested changes

2021-07-03 06:59 UTC, Antoshka007 commented on project/src/components/comment-form/comment-form.jsx
> +    setIsSubmitAvailable((rating >= 1 && rating <= 5) && comment.length >= 50 && comment.length <= 300);
Зачем тут useEffect и isSubmitAvailable в стейте? Можно же просто:
```
isSubmitAvailable = rating >= 1 && rating <= 5 && comment.length >= 50 && comment.length <= 300;
```

2021-07-03 06:59 UTC, Antoshka007 commented on project/src/components/comment-form/comment-form.jsx
> +    setRating(0);
Очищать нужно только после успешной публикации коммента.

2021-07-03 06:59 UTC, Antoshka007 commented on project/src/components/comment-star/comment-start.jsx
> +        checked={rating === stars}
Лучше сразу передавать isChecked, чтобы компонент оставался более изолированным

2021-07-03 06:59 UTC, Antoshka007 commented on project/src/components/login-screen/login-screen.jsx
> +    history.push(AppRoute.ROOT);
У тебя же есть редирект экшен)

2021-07-03 06:59 UTC, Antoshka007 commented on project/src/components/offer/offer.jsx
> +            onClick={() => handleFavoriteClick(offer.isFavorite ? 0 : 1)}
Давай так:
```suggestion
            onClick={handleFavoriteClick}
```
Зачем две функции, если можно обойтись одной)

2021-07-03 06:59 UTC, Antoshka007 commented on project/src/store/reducer.js
> +      });
Можно попроще)
```suggestion
      const updatedOffers = state.offers.map(offer => offer.id === action.payload.offer.id ? action.payload.offer : offer);
```

2021-07-03 21:40 UTC, VadimCpp commented on project/src/components/comment-form/comment-form.jsx
> +    setIsSubmitAvailable((rating >= 1 && rating <= 5) && comment.length >= 50 && comment.length <= 300);
Исправил

2021-07-04 18:56 UTC, VadimCpp commented on project/src/components/offer/offer.jsx
> +            onClick={() => handleFavoriteClick(offer.isFavorite ? 0 : 1)}
Сделано

2021-07-04 18:58 UTC, VadimCpp commented on project/src/store/reducer.js
> +      });
Поправил

2021-07-04 21:14 UTC, Antoshka007 approved these changes
ПР принимаю, но обрати внимание на то, что у тебя isFavorite в nearby-офферах не обновляется при клике на кнопку. Поправь в следующем.

2021-07-04 21:14 UTC, merged