Module7 task1
htmlacademy-react/78842-six-cities-7 pull request #16
Opened 2021-07-06 17:45 UTC by VadimCpp

2021-07-07 16:49 UTC, Antoshka007 requested changes
1. Если авторизоваться, перейти на favorites и обновить страницу, то перенаправит на главный экран.
2. Ловлю такие ошибки:
<img width="1680" alt="Screen Shot 2021-07-07 at 6 59 57 PM" src="https://user-images.githubusercontent.com/8845366/124798614-38ed6780-df5c-11eb-87ee-7dbb62247613.png">
<img width="1680" alt="Screen Shot 2021-07-07 at 7 31 28 PM" src="https://user-images.githubusercontent.com/8845366/124798661-486cb080-df5c-11eb-9090-dfa635da8519.png">
3. Надо починить кнопку "Добавить в избранное" в nearby-предложениях.

2021-07-07 16:49 UTC, Antoshka007 commented on project/src/components/cities/cities.jsx
> +                  evt.preventDefault();
Это же span, зачем тут preventDefault?

2021-07-07 16:49 UTC, Antoshka007 commented on project/src/components/login-screen/login-screen.jsx
> +    evt.preventDefault();
Тут тоже preventDefault не нужен

2021-07-07 16:49 UTC, Antoshka007 commented on project/src/components/room-screen/room-screen.jsx
> +    return null;
Может редирект тут запилим на 404?

2021-07-07 16:49 UTC, Antoshka007 commented on project/src/components/room/room.jsx
> +            <button className="property__bookmark-button button" type="button">
Оказывается, тут всё-таки есть кнопка, но её не видно в интерфейсе. Надо зачинить)

2021-07-07 16:49 UTC, Antoshka007 commented on project/src/store/action.js
> +export const setCity = createAction(ActionType.SET_CITY, (city) => ({
Можно ещё сократить, отказавшись от второго аргумента.
Redux Toolkit автоматически положит данные в payload: https://redux-toolkit.js.org/api/createAction

2021-07-07 16:49 UTC, Antoshka007 commented on project/src/store/action.js
> +}));
Вот так имею в виду:
```suggestion
export const requireAuthorization = createAction(ActionType.REQUIRED_AUTHORIZATION);
```

2021-07-07 17:19 UTC, merged

2021-07-08 09:07 UTC, VadimCpp commented on project/src/components/cities/cities.jsx
> +                  evt.preventDefault();
Исправлено

2021-07-08 09:08 UTC, VadimCpp commented on project/src/components/login-screen/login-screen.jsx
> +    evt.preventDefault();
Исправлено

2021-07-08 09:15 UTC, VadimCpp commented on project/src/components/room-screen/room-screen.jsx
> +    return null;
Сделал спиннер

2021-07-08 09:31 UTC, VadimCpp commented on project/src/store/action.js
> +export const setCity = createAction(ActionType.SET_CITY, (city) => ({
Круто, сделал

2021-07-08 10:05 UTC, VadimCpp commented on project/src/components/room/room.jsx
> +            <button className="property__bookmark-button button" type="button">
Исправлено

2021-07-08 10:28 UTC, VadimCpp commented
Все замечания исправлены